use std::{collections::BTreeMap, error::Error};

use crate::{
    codegen::{
        OpenApiSchema, OpenApiSpec,
        shared::{self, ConflictBehavior, TupleField},
        strip_schema_ref_prefix,
    },
    util::codegen_buf::CodegenBuf,
};

pub fn render(mut spec: OpenApiSpec) -> Result<CodegenBuf, Box<dyn Error>> {
    shared::extract_any_of_tuples(&mut spec.managed_schemas, ConflictBehavior::AppendSuffix)?;
    let ctx = RenderCtx {
        inherits: compute_inherits(&spec.managed_schemas)?,
        objects_as_tuples: rewrite_single_field_objects_to_tuples(&mut spec.managed_schemas)?,
        schemas: spec.managed_schemas,
    };

    let mut buf = CodegenBuf::default();

    buf.writeln("// Code generated by turbopuffer-apigen. DO NOT EDIT.");
    buf.writeln("");
    buf.writeln("using System;");
    buf.writeln("using System.Collections.Generic;");
    buf.writeln("using System.Text.Json;");
    buf.writeln("using System.Text.Json.Serialization;");
    buf.writeln("");
    buf.writeln("namespace Turbopuffer.Models.Namespaces;");
    buf.writeln("");

    for (i, (name, schema)) in ctx.schemas.iter().enumerate() {
        if i > 0 {
            buf.writeln("");
        }
        render_schema_top_level(&ctx, &mut buf, name, schema)?;
    }

    Ok(buf)
}

struct RenderCtx {
    inherits: BTreeMap<String, String>,
    /// Names of objects that have been munged into tuples, and any JSON name
    /// overrides for the fields.
    objects_as_tuples: BTreeMap<String, BTreeMap<String, String>>,
    schemas: BTreeMap<String, OpenApiSchema>,
}

fn compute_inherits(
    schemas: &BTreeMap<String, OpenApiSchema>,
) -> Result<BTreeMap<String, String>, Box<dyn Error>> {
    let mut result = BTreeMap::new();
    for (name, schema) in schemas {
        if let OpenApiSchema::AnyOf {
            _description: _,
            any_of,
        } = schema
        {
            for schema in any_of {
                if let OpenApiSchema::Ref { sref, .. } = schema {
                    let sref = strip_schema_ref_prefix(sref)?;
                    let existing = result.insert(sref.into(), name.into());
                    if let Some(existing) = existing {
                        Err(format!(
                            "duplicate inheritance for {sref}: {existing} and {name}"
                        ))?
                    }
                }
            }
        }
    }
    Ok(result)
}

fn rewrite_single_field_objects_to_tuples(
    schemas: &mut BTreeMap<String, OpenApiSchema>,
) -> Result<BTreeMap<String, BTreeMap<String, String>>, Box<dyn Error>> {
    let mut names = BTreeMap::new();
    for (name, schema) in schemas {
        if let OpenApiSchema::Object {
            _description: _,
            _type: _,
            properties,
            required,
            title: _,
        } = schema
        {
            if properties.len() == 1 && required.len() == 1 {
                let (prop_name, prop_schema) = properties.iter().next().unwrap();
                if !required.contains(prop_name) {
                    continue;
                }
                let prop_name = prop_name.clone();
                let prop_name_munged = shared::snake_to_camel_case(&prop_name);
                let mut prop_schema = prop_schema.clone();
                if let Some(title) = prop_schema.title_mut() {
                    *title = Some(prop_name_munged.clone());
                }
                *schema = OpenApiSchema::ArrayTuple {
                    prefix_items: vec![prop_schema],
                    _description: None,
                    _type: Default::default(),
                    additional_items: false,
                    x_turbopuffer_variant_name: None,
                    x_turbopuffer_variant_drop_on_conflict: false,
                    title: None,
                };
                let overrides = BTreeMap::from([(prop_name_munged, prop_name)]);
                names.insert(name.clone(), overrides);
            }
        }
    }
    Ok(names)
}

fn render_schema_top_level(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    name: &str,
    schema: &OpenApiSchema,
) -> Result<(), Box<dyn Error>> {
    match schema {
        OpenApiSchema::AnyOf {
            _description: _,
            any_of,
        } => {
            if any_of
                .iter()
                .all(|s| matches!(s, OpenApiSchema::Const { .. }))
            {
                render_any_of_const_enum(buf, name, any_of)?;
            } else if any_of
                .iter()
                .all(|s| matches!(s, OpenApiSchema::Ref { .. }))
            {
                render_any_of_refs(ctx, buf, name, any_of)?;
            } else {
                Err("unsupported anyOf")?
            }
        }
        OpenApiSchema::ArrayList { items, .. } => {
            // Top-level array list becomes a wrapper class whose contents
            // serialize transparently as a JSON array of items.
            render_class_header(ctx, buf, name);
            buf.indent();
            buf.start_line();
            buf.write("public ");
            render_schema_inline(ctx, buf, items)?;
            buf.write("[] Items { get; }");
            buf.end_line();
            buf.writeln("");
            buf.start_line();
            buf.write(format!("public {name}("));
            render_schema_inline(ctx, buf, items)?;
            buf.write("[] items)");
            buf.end_line();
            buf.writeln("{");
            buf.indent();
            buf.writeln("this.Items = items;");
            buf.unindent();
            buf.writeln("}");
            buf.writeln("");
            render_write_json_override(ctx, buf, |buf| {
                buf.writeln("writer.WriteStartArray();");
                buf.writeln("foreach (var item in this.Items)");
                buf.writeln("{");
                buf.indent();
                buf.writeln("JsonSerializer.Serialize(writer, item, options);");
                buf.unindent();
                buf.writeln("}");
                buf.writeln("writer.WriteEndArray();");
                Ok::<_, Box<dyn Error>>(())
            })?;
            buf.unindent();
            buf.writeln("}");
        }
        OpenApiSchema::String { .. } => {
            // Top-level string becomes a wrapper class that serializes
            // transparently as the underlying string.
            render_class_header(ctx, buf, name);
            buf.indent();
            buf.writeln("public string Value { get; }");
            buf.writeln("");
            buf.writeln(format!("public {name}(string value)"));
            buf.writeln("{");
            buf.indent();
            buf.writeln("this.Value = value;");
            buf.unindent();
            buf.writeln("}");
            buf.writeln("");
            render_write_json_override(ctx, buf, |buf| {
                buf.writeln("writer.WriteStringValue(this.Value);");
                Ok::<_, Box<dyn Error>>(())
            })?;
            buf.unindent();
            buf.writeln("}");
        }
        OpenApiSchema::Map {
            additional_properties,
            ..
        } => {
            // Top-level map becomes a wrapper class with a Name and Value
            // field that serializes as a singleton object `{<name>: <value>}`.
            let value_schema = &**additional_properties;
            render_class_header(ctx, buf, name);
            buf.indent();
            buf.writeln("public string Name { get; }");
            buf.start_line();
            buf.write("public ");
            render_schema_inline(ctx, buf, value_schema)?;
            buf.write(" Value { get; }");
            buf.end_line();
            buf.writeln("");
            buf.start_line();
            buf.write(format!("public {name}(string name, "));
            render_schema_inline(ctx, buf, value_schema)?;
            buf.write(" value)");
            buf.end_line();
            buf.writeln("{");
            buf.indent();
            buf.writeln("this.Name = name;");
            buf.writeln("this.Value = value;");
            buf.unindent();
            buf.writeln("}");
            buf.writeln("");
            render_write_json_override(ctx, buf, |buf| {
                buf.writeln("writer.WriteStartObject();");
                buf.writeln("writer.WritePropertyName(this.Name);");
                buf.writeln("JsonSerializer.Serialize(writer, this.Value, options);");
                buf.writeln("writer.WriteEndObject();");
                Ok::<_, Box<dyn Error>>(())
            })?;
            buf.unindent();
            buf.writeln("}");
        }
        OpenApiSchema::ArrayTuple {
            additional_items: true,
            ..
        } => Err("tuple-type arrays with `items: true` unsupported")?,
        OpenApiSchema::ArrayTuple {
            prefix_items,
            additional_items: false,
            ..
        } => {
            render_array_tuple_class(ctx, buf, name, prefix_items)?;
        }
        OpenApiSchema::Object { .. } => Err("object schemas in top-level unsupported")?,
        _ => Err("schema type not supported at top level")?,
    }
    Ok(())
}

fn render_class_header(ctx: &RenderCtx, buf: &mut CodegenBuf, name: &str) {
    buf.start_line();
    buf.write(format!("public sealed class {name}"));
    if let Some(parent) = ctx.inherits.get(name) {
        buf.write(format!(" : {parent}"));
    } else {
        // Stand-alone wrapper classes don't have a polymorphic base, but they
        // still need to participate in the JsonSerializer dispatch, so attach a
        // dedicated converter.
        // (Handled by the [JsonConverter] attribute emitted on the parent
        // abstract type; here we just emit nothing.)
    }
    buf.end_line();
    buf.writeln("{");
}

fn render_write_json_override<F>(
    _ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    body: F,
) -> Result<(), Box<dyn Error>>
where
    F: FnOnce(&mut CodegenBuf) -> Result<(), Box<dyn Error>>,
{
    buf.writeln(
        "internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)",
    );
    buf.writeln("{");
    buf.indent();
    body(buf)?;
    buf.unindent();
    buf.writeln("}");
    Ok(())
}

fn render_array_tuple_class(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    name: &str,
    prefix_items: &[OpenApiSchema],
) -> Result<(), Box<dyn Error>> {
    let fields = shared::build_tuple_fields(prefix_items);
    let parent = ctx.inherits.get(name);
    let parent_factory_names = parent
        .map(|p| collect_factory_names(ctx, p))
        .unwrap_or_default();

    buf.start_line();
    buf.write(format!("public sealed class {name}"));
    if let Some(parent) = parent {
        buf.write(format!(" : {parent}"));
    }
    buf.end_line();
    buf.writeln("{");
    buf.indent();

    // Public properties.
    for field in &fields {
        if let TupleField::Normal { name: prop_name, schema } = field {
            let prop_name_pascal = pascal_case(prop_name);
            buf.start_line();
            buf.write("public ");
            // If the property name collides with a factory method on a parent
            // class, use the `new` keyword to suppress the C# CS0108 warning.
            if parent_factory_names.contains(&prop_name_pascal) {
                buf.write("new ");
            }
            render_schema_inline(ctx, buf, schema)?;
            buf.write(format!(" {prop_name_pascal} {{ get; }}"));
            buf.end_line();
        }
    }
    buf.writeln("");

    // Constructor.
    let normal_fields: Vec<_> = fields
        .iter()
        .filter_map(|f| match f {
            TupleField::Normal { name, schema } => Some((name.clone(), schema)),
            TupleField::Const(_) => None,
        })
        .collect();

    buf.start_line();
    buf.write(format!("public {name}("));
    for (i, (prop_name, schema)) in normal_fields.iter().enumerate() {
        if i > 0 {
            buf.write(", ");
        }
        render_schema_inline(ctx, buf, schema)?;
        buf.write(format!(" {}", camel_case(prop_name)));
    }
    buf.write(")");
    buf.end_line();
    buf.writeln("{");
    buf.indent();
    for (prop_name, _) in &normal_fields {
        let pascal = pascal_case(prop_name);
        let camel = camel_case(prop_name);
        buf.writeln(format!("this.{pascal} = {camel};"));
    }
    buf.unindent();
    buf.writeln("}");
    buf.writeln("");

    // WriteJson override.
    let json_overrides = ctx.objects_as_tuples.get(name);
    render_write_json_override(ctx, buf, |buf| {
        if json_overrides.is_some() {
            // Serialize as an object using overridden field names.
            buf.writeln("writer.WriteStartObject();");
        } else {
            buf.writeln("writer.WriteStartArray();");
        }
        for field in &fields {
            match field {
                TupleField::Const(sconst) => {
                    buf.writeln(format!("writer.WriteStringValue(\"{sconst}\");"));
                }
                TupleField::Normal { name: prop_name, schema: _ } => {
                    let pascal = pascal_case(prop_name);
                    if let Some(overrides) = json_overrides {
                        let json_name = overrides
                            .get(prop_name)
                            .cloned()
                            .unwrap_or_else(|| prop_name.clone());
                        buf.writeln(format!(
                            "writer.WritePropertyName(\"{}\");",
                            json_name.replace('\\', "\\\\").replace('"', "\\\"")
                        ));
                    }
                    buf.writeln(format!(
                        "JsonSerializer.Serialize(writer, this.{pascal}, options);"
                    ));
                }
            }
        }
        if json_overrides.is_some() {
            buf.writeln("writer.WriteEndObject();");
        } else {
            buf.writeln("writer.WriteEndArray();");
        }
        Ok::<_, Box<dyn Error>>(())
    })?;
    buf.unindent();
    buf.writeln("}");
    Ok(())
}

fn render_any_of_const_enum(
    buf: &mut CodegenBuf,
    name: &str,
    schema: &[OpenApiSchema],
) -> Result<(), Box<dyn Error>> {
    // String-style enum backed by `JsonStringEnumConverter`. We rely on the
    // built-in converter (no naming policy) so the JSON values must match the
    // enum member names. The spec uses lower-case values, so we apply a custom
    // converter inline.

    let mut entries = vec![];
    for item in schema {
        let OpenApiSchema::Const {
            _description: _,
            title: x_turbopuffer_name,
            sconst,
        } = item
        else {
            unreachable!("validated by render_schema_top_level");
        };
        let member_name = x_turbopuffer_name.clone().unwrap_or_else(|| {
            let mut s = String::new();
            let mut chars = sconst.chars();
            if let Some(c) = chars.next() {
                s.extend(c.to_uppercase());
            }
            for c in chars {
                if c.is_uppercase() {
                    s.push('_');
                }
                s.extend(c.to_uppercase());
            }
            s
        });
        entries.push((member_name, sconst.clone()));
    }

    buf.writeln(format!(
        "[JsonConverter(typeof({name}JsonConverter))]"
    ));
    buf.writeln(format!("public enum {name}"));
    buf.writeln("{");
    buf.indent();
    for (member, _) in &entries {
        buf.writeln(format!("{member},"));
    }
    buf.unindent();
    buf.writeln("}");
    buf.writeln("");

    buf.writeln(format!(
        "internal sealed class {name}JsonConverter : JsonConverter<{name}>"
    ));
    buf.writeln("{");
    buf.indent();
    buf.writeln(format!(
        "public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)"
    ));
    buf.writeln("{");
    buf.indent();
    buf.writeln("var s = reader.GetString();");
    buf.writeln("return s switch");
    buf.writeln("{");
    buf.indent();
    for (member, sconst) in &entries {
        buf.writeln(format!("\"{sconst}\" => {name}.{member},"));
    }
    buf.writeln(format!(
        "_ => throw new JsonException($\"Unknown {name} value: {{s}}\"),"
    ));
    buf.unindent();
    buf.writeln("};");
    buf.unindent();
    buf.writeln("}");
    buf.writeln("");
    buf.writeln(format!(
        "public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options)"
    ));
    buf.writeln("{");
    buf.indent();
    buf.writeln("switch (value)");
    buf.writeln("{");
    buf.indent();
    for (member, sconst) in &entries {
        buf.writeln(format!(
            "case {name}.{member}: writer.WriteStringValue(\"{sconst}\"); break;"
        ));
    }
    buf.writeln(format!(
        "default: throw new JsonException($\"Unknown {name} value: {{value}}\");"
    ));
    buf.unindent();
    buf.writeln("}");
    buf.unindent();
    buf.writeln("}");
    buf.unindent();
    buf.writeln("}");
    Ok(())
}

fn render_any_of_refs(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    name: &str,
    schema: &[OpenApiSchema],
) -> Result<(), Box<dyn Error>> {
    // Polymorphic union. Emit an abstract base class with a custom JSON
    // converter; subclasses are emitted elsewhere via the inherits map.

    let parent = ctx.inherits.get(name);

    buf.writeln(format!(
        "[JsonConverter(typeof({name}JsonConverter))]"
    ));
    buf.start_line();
    buf.write(format!("public abstract class {name}"));
    if let Some(parent) = parent {
        buf.write(format!(" : {parent}"));
    }
    buf.end_line();
    buf.writeln("{");
    buf.indent();

    // Constructor protection.
    buf.writeln(format!("protected {name}() {{ }}"));
    buf.writeln("");

    // Abstract WriteJson. Only emit if no parent already declared it.
    if parent.is_none() {
        buf.writeln(
            "internal abstract void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options);",
        );
        buf.writeln("");
    }

    // Factory methods.
    for item in schema {
        let OpenApiSchema::Ref { sref, title } = item else {
            unreachable!("validated by render_schema_top_level");
        };
        let sref = strip_schema_ref_prefix(sref)?;
        let subname = title.as_deref().unwrap_or(sref);
        let factory_name = pascal_case(subname.strip_prefix(name).unwrap_or(subname));
        let factory_name = munge_factory_name(&factory_name);
        match &ctx.schemas[sref] {
            OpenApiSchema::ArrayTuple { prefix_items, .. } => {
                let fields = shared::build_tuple_fields(prefix_items);
                buf.start_line();
                buf.write(format!("public static {sref} {factory_name}("));
                let mut first = true;
                for field in &fields {
                    if let TupleField::Normal { name: prop_name, schema } = field {
                        if !first {
                            buf.write(", ");
                        }
                        first = false;
                        render_schema_inline(ctx, buf, schema)?;
                        buf.write(format!(" {}", camel_case(prop_name)));
                    }
                }
                buf.write(format!(") => new {sref}("));
                let mut first = true;
                for field in &fields {
                    if let TupleField::Normal { name: prop_name, .. } = field {
                        if !first {
                            buf.write(", ");
                        }
                        first = false;
                        buf.write(camel_case(prop_name));
                    }
                }
                buf.write(");");
                buf.end_line();
            }
            OpenApiSchema::ArrayList { items, .. } => {
                buf.start_line();
                buf.write(format!("public static {sref} {factory_name}("));
                render_schema_inline(ctx, buf, items)?;
                buf.write(format!("[] items) => new {sref}(items);"));
                buf.end_line();
            }
            OpenApiSchema::String { .. } => {
                buf.writeln(format!(
                    "public static {sref} {factory_name}(string value) => new {sref}(value);"
                ));
            }
            OpenApiSchema::Map {
                additional_properties,
                ..
            } => {
                let value_schema = &**additional_properties;
                buf.start_line();
                buf.write(format!(
                    "public static {sref} {factory_name}(string name, "
                ));
                render_schema_inline(ctx, buf, value_schema)?;
                buf.write(format!(" value) => new {sref}(name, value);"));
                buf.end_line();
            }
            _ => (),
        }
    }

    buf.unindent();
    buf.writeln("}");
    buf.writeln("");

    // Raw variant. We emit one per abstract type so that subtype-typed
    // properties can still deserialize into a value that satisfies the
    // declared type.
    buf.writeln(format!("public sealed class {name}Raw : {name}"));
    buf.writeln("{");
    buf.indent();
    buf.writeln("public JsonElement Value { get; }");
    buf.writeln("");
    buf.writeln(format!("public {name}Raw(JsonElement value)"));
    buf.writeln("{");
    buf.indent();
    buf.writeln("this.Value = value;");
    buf.unindent();
    buf.writeln("}");
    buf.writeln("");
    render_write_json_override(ctx, buf, |buf| {
        buf.writeln("this.Value.WriteTo(writer);");
        Ok::<_, Box<dyn Error>>(())
    })?;
    buf.unindent();
    buf.writeln("}");
    buf.writeln("");

    // Converter.
    buf.writeln(format!(
        "internal sealed class {name}JsonConverter : JsonConverter<{name}>"
    ));
    buf.writeln("{");
    buf.indent();
    buf.writeln(format!(
        "public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)"
    ));
    buf.writeln("{");
    buf.indent();
    buf.writeln(format!(
        "return new {name}Raw(JsonElement.ParseValue(ref reader));"
    ));
    buf.unindent();
    buf.writeln("}");
    buf.writeln("");
    buf.writeln(format!(
        "public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options)"
    ));
    buf.writeln("{");
    buf.indent();
    buf.writeln("value.WriteJson(writer, options);");
    buf.unindent();
    buf.writeln("}");
    buf.unindent();
    buf.writeln("}");

    Ok(())
}

fn render_schema_inline(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    schema: &OpenApiSchema,
) -> Result<(), Box<dyn Error>> {
    match schema {
        OpenApiSchema::AnyOf { .. } => {
            // Inline anyOfs aren't named, so we fall back to `object?` for
            // C# representation. Typically the input spec extracts these to
            // named refs via `extract_any_of_tuples`.
            buf.write("object");
        }
        OpenApiSchema::Object { .. } => Err("inline object schemas unsupported")?,
        OpenApiSchema::Map {
            additional_properties,
            ..
        } => {
            buf.write("IReadOnlyDictionary<string, ");
            render_schema_inline(ctx, buf, additional_properties)?;
            buf.write(">");
        }
        OpenApiSchema::ArrayList { items, .. } => {
            render_schema_inline(ctx, buf, items)?;
            buf.write("[]");
        }
        OpenApiSchema::ArrayTuple { .. } => {
            Err("inline array tuple unsupported")?;
        }
        OpenApiSchema::String { .. } => buf.write("string"),
        OpenApiSchema::Boolean { .. } => buf.write("bool"),
        OpenApiSchema::Number {
            x_turbopuffer_width,
            ..
        } => match x_turbopuffer_width {
            Some(32) => buf.write("float"),
            None | Some(64) => buf.write("double"),
            Some(w) => Err(format!("unsupported number width: {w}"))?,
        },
        OpenApiSchema::Const { .. } => Err("inline const in unsupported position")?,
        OpenApiSchema::Ref { sref, .. } => {
            let n = strip_schema_ref_prefix(sref)?;
            buf.write(n);
        }
        OpenApiSchema::Any { .. } => buf.write("object"),
    }
    Ok(())
}

/// Collects the names of factory methods that would be emitted on the given
/// abstract type (and its ancestors), so that subclass property declarations
/// can use the `new` keyword to suppress hiding warnings.
fn collect_factory_names(ctx: &RenderCtx, name: &str) -> std::collections::BTreeSet<String> {
    let mut out = std::collections::BTreeSet::new();
    let mut current = Some(name.to_string());
    while let Some(cur) = current {
        if let Some(OpenApiSchema::AnyOf { any_of, .. }) = ctx.schemas.get(&cur) {
            for item in any_of {
                if let OpenApiSchema::Ref { sref, title } = item {
                    let Ok(sref) = strip_schema_ref_prefix(sref) else {
                        continue;
                    };
                    // No factory is emitted for variants whose target is
                    // itself an AnyOf (those become abstract sub-types).
                    if matches!(ctx.schemas.get(sref), Some(OpenApiSchema::AnyOf { .. })) {
                        continue;
                    }
                    let subname = title.as_deref().unwrap_or(sref);
                    let factory_name = pascal_case(subname.strip_prefix(&cur).unwrap_or(subname));
                    out.insert(factory_name);
                }
            }
        }
        current = ctx.inherits.get(&cur).cloned();
    }
    out
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut chars = s.chars().peekable();
    let mut next_upper = true;
    while let Some(c) = chars.next() {
        if c == '_' {
            next_upper = true;
        } else if next_upper {
            out.extend(c.to_uppercase());
            next_upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn camel_case(s: &str) -> String {
    let pc = pascal_case(s);
    let mut chars = pc.chars();
    let mut out = String::new();
    if let Some(c) = chars.next() {
        out.extend(c.to_lowercase());
    }
    out.extend(chars);
    escape_csharp_keyword(&out)
}

fn escape_csharp_keyword(s: &str) -> String {
    // Prefix with `@` to allow using a C# reserved keyword as an identifier.
    match s {
        "abstract" | "as" | "base" | "bool" | "break" | "byte" | "case" | "catch" | "char"
        | "checked" | "class" | "const" | "continue" | "decimal" | "default" | "delegate"
        | "do" | "double" | "else" | "enum" | "event" | "explicit" | "extern" | "false"
        | "finally" | "fixed" | "float" | "for" | "foreach" | "goto" | "if" | "implicit"
        | "in" | "int" | "interface" | "internal" | "is" | "lock" | "long" | "namespace"
        | "new" | "null" | "object" | "operator" | "out" | "override" | "params" | "private"
        | "protected" | "public" | "readonly" | "ref" | "return" | "sbyte" | "sealed"
        | "short" | "sizeof" | "stackalloc" | "static" | "string" | "struct" | "switch"
        | "this" | "throw" | "true" | "try" | "typeof" | "uint" | "ulong" | "unchecked"
        | "unsafe" | "ushort" | "using" | "virtual" | "void" | "volatile" | "while" => {
            format!("@{s}")
        }
        _ => s.to_string(),
    }
}

fn munge_factory_name(s: &str) -> String {
    // Avoid C# reserved keywords as method names.
    match s {
        "In" | "Default" | "New" => s.to_string(), // these are fine as method names
        _ => s.to_string(),
    }
}
