use std::{
    collections::{BTreeMap, BTreeSet},
    error::Error,
};

use crate::{
    codegen::{
        OpenApiSchema, OpenApiSpec,
        shared::{self, ConflictBehavior, TupleField},
        strip_schema_ref_prefix,
    },
    util::codegen_buf::CodegenBuf,
};

pub fn render(mut spec: OpenApiSpec) -> Result<CodegenBuf, Box<dyn Error>> {
    shared::extract_any_of_tuples(&mut spec.managed_schemas, ConflictBehavior::AppendSuffix)?;
    let ctx = RenderCtx {
        inherits: shared::compute_inherits(&spec.managed_schemas)?,
        objects_as_tuples: shared::rewrite_single_field_objects_to_tuples(
            &mut spec.managed_schemas,
        )?,
        schemas: spec.managed_schemas,
    };

    let mut buf = CodegenBuf::default();

    buf.writeln("// Code generated by turbopuffer-apigen. DO NOT EDIT.");
    buf.writeln("");
    buf.writeln("using System;");
    buf.writeln("using System.Text.Json;");
    buf.writeln("using System.Text.Json.Serialization;");
    buf.writeln("");
    buf.writeln("namespace Turbopuffer.Models.Namespaces;");
    buf.writeln("");

    for (i, (name, schema)) in ctx.schemas.iter().enumerate() {
        if i > 0 {
            buf.writeln("");
        }
        render_schema_top_level(&ctx, &mut buf, name, schema)?;
    }

    Ok(buf)
}

struct RenderCtx {
    /// Maps each variant schema name to the name of the abstract base it
    /// belongs to (its enclosing `anyOf` schema).
    inherits: BTreeMap<String, String>,
    /// Names of objects that have been munged into tuples, and the JSON name
    /// overrides for their fields (`pascal -> original`).
    objects_as_tuples: BTreeMap<String, BTreeMap<String, String>>,
    schemas: BTreeMap<String, OpenApiSchema>,
}

/// Formats the list of generics returned by [`shared::assign_generics`] as the
/// `<T, U, ...>` suffix that C# splices after both the class name and the
/// factory method name. Empty string when no generics were assigned.
fn format_generics(generics: &[&str]) -> String {
    if generics.is_empty() {
        String::new()
    } else {
        format!("<{}>", generics.join(", "))
    }
}

fn render_schema_top_level(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    name: &str,
    schema: &OpenApiSchema,
) -> Result<(), Box<dyn Error>> {
    match schema {
        OpenApiSchema::AnyOf { any_of, .. } => {
            if any_of
                .iter()
                .all(|s| matches!(s, OpenApiSchema::Const { .. }))
            {
                render_any_of_const_enum(buf, name, any_of)?;
            } else if any_of
                .iter()
                .all(|s| matches!(s, OpenApiSchema::Ref { .. }))
            {
                render_any_of_refs(ctx, buf, name, any_of)?;
            } else {
                Err("unsupported anyOf")?
            }
        }
        OpenApiSchema::ArrayList { items, .. } => {
            render_wrapper_class(
                ctx,
                buf,
                name,
                |buf| {
                    buf.start_line();
                    buf.write("public ");
                    render_schema_inline(buf, items)?;
                    buf.write("[] Items { get; } = items;");
                    buf.end_line();
                    Ok(())
                },
                |buf| {
                    render_schema_inline(buf, items)?;
                    buf.write("[] items");
                    Ok(())
                },
                |buf| {
                    buf.writeln("writer.WriteStartArray();");
                    buf.writeln("foreach (var item in this.Items)");
                    buf.writeln("{");
                    buf.indent();
                    buf.writeln("JsonSerializer.Serialize(writer, item, options);");
                    buf.unindent();
                    buf.writeln("}");
                    buf.writeln("writer.WriteEndArray();");
                    Ok(())
                },
            )?;
        }
        OpenApiSchema::String { .. } => {
            render_wrapper_class(
                ctx,
                buf,
                name,
                |buf| {
                    buf.writeln("public string Value { get; } = value;");
                    Ok(())
                },
                |buf| {
                    buf.write("string value");
                    Ok(())
                },
                |buf| {
                    buf.writeln("writer.WriteStringValue(this.Value);");
                    Ok(())
                },
            )?;
        }
        OpenApiSchema::Map {
            additional_properties,
            ..
        } => {
            let value_schema = &**additional_properties;
            render_wrapper_class(
                ctx,
                buf,
                name,
                |buf| {
                    buf.writeln("public string Name { get; } = name;");
                    buf.start_line();
                    buf.write("public ");
                    render_schema_inline(buf, value_schema)?;
                    buf.write(" Value { get; } = value;");
                    buf.end_line();
                    Ok(())
                },
                |buf| {
                    buf.write("string name, ");
                    render_schema_inline(buf, value_schema)?;
                    buf.write(" value");
                    Ok(())
                },
                |buf| {
                    buf.writeln("writer.WriteStartObject();");
                    buf.writeln("writer.WritePropertyName(this.Name);");
                    buf.writeln("JsonSerializer.Serialize(writer, this.Value, options);");
                    buf.writeln("writer.WriteEndObject();");
                    Ok(())
                },
            )?;
        }
        OpenApiSchema::ArrayTuple {
            additional_items: true,
            ..
        } => Err("tuple-type arrays with `items: true` unsupported")?,
        OpenApiSchema::ArrayTuple { prefix_items, .. } => {
            render_array_tuple_class(ctx, buf, name, prefix_items)?;
        }
        OpenApiSchema::Object { .. } => Err("object schemas in top-level unsupported")?,
        _ => Err("schema type not supported at top level")?,
    }
    Ok(())
}

/// Emits a `sealed class Name(<ctor params>) : Parent { <properties>;
/// internal override void WriteJson(...) { <body> } }` block.
fn render_wrapper_class<P, C, W>(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    name: &str,
    render_properties: P,
    render_ctor_params: C,
    render_write_body: W,
) -> Result<(), Box<dyn Error>>
where
    P: FnOnce(&mut CodegenBuf) -> Result<(), Box<dyn Error>>,
    C: FnOnce(&mut CodegenBuf) -> Result<(), Box<dyn Error>>,
    W: FnOnce(&mut CodegenBuf) -> Result<(), Box<dyn Error>>,
{
    let parent = ctx
        .inherits
        .get(name)
        .map(String::as_str)
        .unwrap_or_default();
    // Pin the base's converter onto the concrete subtype too. STJ resolves
    // converters from the static type, and JsonConverterAttribute is not
    // inherited, so without this the type serializes via default reflection
    // when used boxed as itself instead of as its abstract base.
    if !parent.is_empty() {
        buf.writeln(format!("[JsonConverter(typeof({parent}JsonConverter))]"));
    }
    buf.start_line();
    buf.write(format!("public sealed class {name}("));
    render_ctor_params(buf)?;
    if parent.is_empty() {
        buf.write(")");
    } else {
        buf.write(format!(") : {parent}"));
    }
    buf.end_line();
    buf.writeln("{");
    buf.indent();
    render_properties(buf)?;
    buf.writeln("");
    render_write_json_override(buf, render_write_body)?;
    buf.unindent();
    buf.writeln("}");
    Ok(())
}

fn render_write_json_override<F>(buf: &mut CodegenBuf, body: F) -> Result<(), Box<dyn Error>>
where
    F: FnOnce(&mut CodegenBuf) -> Result<(), Box<dyn Error>>,
{
    buf.writeln(
        "internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)",
    );
    buf.writeln("{");
    buf.indent();
    body(buf)?;
    buf.unindent();
    buf.writeln("}");
    Ok(())
}

fn render_array_tuple_class(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    name: &str,
    prefix_items: &[OpenApiSchema],
) -> Result<(), Box<dyn Error>> {
    // Replace `object[]`-typed (i.e. `items: any`) list fields with generic
    // type parameters `T[]`, `U[]`, ... so callers can pass strongly-typed
    // arrays without per-element casts to `object`.
    let mut prefix_items = prefix_items.to_vec();
    let generics = format_generics(&shared::assign_generics(&mut prefix_items));

    let fields = shared::build_tuple_fields(&prefix_items);
    let parent = ctx.inherits.get(name);
    let parent_factory_names = parent
        .map(|p| collect_factory_names(ctx, p))
        .unwrap_or_default();
    let json_overrides = ctx.objects_as_tuples.get(name);
    let normal_fields: Vec<_> = fields
        .iter()
        .filter_map(|f| match f {
            TupleField::Normal { name, schema } => Some((name.as_str(), *schema)),
            TupleField::Const(_) => None,
        })
        .collect();

    // Class declaration with primary constructor. Omit the `()` when there
    // are no parameters so the default ctor is implicit.
    //
    // Pin the base's converter onto the concrete subtype (see the comment in
    // `render_wrapper_class`).
    if let Some(parent) = parent {
        buf.writeln(format!("[JsonConverter(typeof({parent}JsonConverter))]"));
    }
    buf.start_line();
    buf.write(format!("public sealed class {name}{generics}"));
    if !normal_fields.is_empty() {
        buf.write("(");
        for (i, (prop_name, schema)) in normal_fields.iter().enumerate() {
            if i > 0 {
                buf.write(", ");
            }
            render_schema_inline(buf, schema)?;
            buf.write(format!(" {}", camel_case(prop_name)));
        }
        buf.write(")");
    }
    if let Some(parent) = parent {
        buf.write(format!(" : {parent}"));
    }
    buf.end_line();
    buf.writeln("{");
    buf.indent();

    // Public properties bound to the primary constructor parameters.
    for (prop_name, schema) in &normal_fields {
        let prop_pascal = pascal_case(prop_name);
        let ctor_arg = camel_case(prop_name);
        buf.start_line();
        buf.write("public ");
        // If the property name collides with a factory method on a parent
        // class, use the `new` keyword to suppress C# CS0108.
        if parent_factory_names.contains(&prop_pascal) {
            buf.write("new ");
        }
        render_schema_inline(buf, schema)?;
        buf.write(format!(" {prop_pascal} {{ get; }} = {ctor_arg};"));
        buf.end_line();
    }
    if !normal_fields.is_empty() {
        buf.writeln("");
    }

    // WriteJson override.
    let as_object = json_overrides.is_some();
    render_write_json_override(buf, |buf| {
        buf.writeln(if as_object {
            "writer.WriteStartObject();"
        } else {
            "writer.WriteStartArray();"
        });
        for field in &fields {
            match field {
                TupleField::Const(sconst) => {
                    buf.writeln(format!("writer.WriteStringValue(\"{sconst}\");"));
                }
                TupleField::Normal {
                    name: prop_name, ..
                } => {
                    if let Some(overrides) = json_overrides {
                        let json_name = overrides
                            .get(prop_name)
                            .map(String::as_str)
                            .unwrap_or(prop_name);
                        buf.writeln(format!(
                            "writer.WritePropertyName({});",
                            escape_csharp_string(json_name)
                        ));
                    }
                    buf.writeln(format!(
                        "JsonSerializer.Serialize(writer, this.{}, options);",
                        pascal_case(prop_name)
                    ));
                }
            }
        }
        buf.writeln(if as_object {
            "writer.WriteEndObject();"
        } else {
            "writer.WriteEndArray();"
        });
        Ok(())
    })?;
    buf.unindent();
    buf.writeln("}");
    Ok(())
}

fn render_any_of_const_enum(
    buf: &mut CodegenBuf,
    name: &str,
    schema: &[OpenApiSchema],
) -> Result<(), Box<dyn Error>> {
    let entries: Vec<_> = schema
        .iter()
        .map(|item| {
            let OpenApiSchema::Const { title, sconst, .. } = item else {
                unreachable!("validated by caller");
            };
            let member = title
                .clone()
                .unwrap_or_else(|| sconst_to_screaming_snake(sconst));
            (member, sconst.clone())
        })
        .collect();

    buf.writeln(format!("[JsonConverter(typeof({name}JsonConverter))]"));
    buf.writeln(format!("public enum {name}"));
    buf.writeln("{");
    buf.indent();
    for (member, _) in &entries {
        buf.writeln(format!("{member},"));
    }
    buf.unindent();
    buf.writeln("}");
    buf.writeln("");

    buf.writeln(format!(
        "internal sealed class {name}JsonConverter : JsonConverter<{name}>"
    ));
    buf.writeln("{");
    buf.indent();

    // Read.
    buf.writeln(format!(
        "public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>"
    ));
    buf.indent();
    buf.writeln("reader.GetString() switch");
    buf.writeln("{");
    buf.indent();
    for (member, sconst) in &entries {
        buf.writeln(format!("\"{sconst}\" => {name}.{member},"));
    }
    buf.writeln(format!(
        "var s => throw new JsonException($\"Unknown {name} value: {{s}}\"),"
    ));
    buf.unindent();
    buf.writeln("};");
    buf.unindent();
    buf.writeln("");

    // Write.
    buf.writeln(format!(
        "public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options) =>"
    ));
    buf.indent();
    buf.writeln("writer.WriteStringValue(value switch");
    buf.writeln("{");
    buf.indent();
    for (member, sconst) in &entries {
        buf.writeln(format!("{name}.{member} => \"{sconst}\","));
    }
    buf.writeln(format!(
        "_ => throw new JsonException($\"Unknown {name} value: {{value}}\"),"
    ));
    buf.unindent();
    buf.writeln("});");
    buf.unindent();
    buf.unindent();
    buf.writeln("}");
    Ok(())
}

fn render_any_of_refs(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    name: &str,
    schema: &[OpenApiSchema],
) -> Result<(), Box<dyn Error>> {
    let parent = ctx.inherits.get(name);

    // Abstract base.
    buf.writeln(format!("[JsonConverter(typeof({name}JsonConverter))]"));
    buf.start_line();
    buf.write(format!("public abstract class {name}"));
    if let Some(parent) = parent {
        buf.write(format!(" : {parent}"));
    }
    buf.end_line();
    buf.writeln("{");
    buf.indent();

    // Abstract WriteJson; only declared at the root of the hierarchy.
    if parent.is_none() {
        buf.writeln(
            "internal abstract void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options);",
        );
        buf.writeln("");
    }

    // Factory methods.
    for item in schema {
        let OpenApiSchema::Ref { sref, title } = item else {
            unreachable!("validated by caller");
        };
        let sref = strip_schema_ref_prefix(sref)?;
        let subname = title.as_deref().unwrap_or(sref);
        let factory_name = pascal_case(subname.strip_prefix(name).unwrap_or(subname));
        render_factory(ctx, buf, sref, &factory_name)?;
    }

    buf.unindent();
    buf.writeln("}");
    buf.writeln("");

    // Raw variant — one per abstract type so that subtype-typed properties
    // still deserialize into a value that satisfies the declared type.
    buf.writeln(format!("[JsonConverter(typeof({name}JsonConverter))]"));
    buf.writeln(format!(
        "public sealed class {name}Raw(JsonElement value) : {name}"
    ));
    buf.writeln("{");
    buf.indent();
    buf.writeln("public JsonElement Value { get; } = value;");
    buf.writeln("");
    buf.writeln(
        "internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>",
    );
    buf.indent();
    buf.writeln("this.Value.WriteTo(writer);");
    buf.unindent();
    buf.unindent();
    buf.writeln("}");
    buf.writeln("");

    // Converter.
    buf.writeln(format!(
        "internal sealed class {name}JsonConverter : JsonConverter<{name}>"
    ));
    buf.writeln("{");
    buf.indent();
    // Accept any subtype, not just the abstract base, so this converter can be
    // pinned onto the concrete subtypes via JsonConverterAttribute.
    buf.writeln("public override bool CanConvert(Type typeToConvert) =>");
    buf.indent();
    buf.writeln(format!("typeof({name}).IsAssignableFrom(typeToConvert);"));
    buf.unindent();
    buf.writeln("");
    buf.writeln(format!(
        "public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>"
    ));
    buf.indent();
    buf.writeln(format!(
        "new {name}Raw(JsonElement.ParseValue(ref reader));"
    ));
    buf.unindent();
    buf.writeln("");
    buf.writeln(format!(
        "public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options) =>"
    ));
    buf.indent();
    buf.writeln("value.WriteJson(writer, options);");
    buf.unindent();
    buf.unindent();
    buf.writeln("}");

    Ok(())
}

fn render_factory(
    ctx: &RenderCtx,
    buf: &mut CodegenBuf,
    sref: &str,
    factory_name: &str,
) -> Result<(), Box<dyn Error>> {
    match &ctx.schemas[sref] {
        OpenApiSchema::ArrayTuple { prefix_items, .. } => {
            let mut prefix_items = prefix_items.clone();
            let generics = format_generics(&shared::assign_generics(&mut prefix_items));
            let fields = shared::build_tuple_fields(&prefix_items);
            let normal_fields: Vec<_> = fields
                .iter()
                .filter_map(|f| match f {
                    TupleField::Normal { name, schema } => Some((name.as_str(), *schema)),
                    _ => None,
                })
                .collect();
            buf.start_line();
            buf.write(format!(
                "public static {sref}{generics} {factory_name}{generics}("
            ));
            // Mirror the Java backend: a list field is emitted variadically
            // (`params T[]`) only when it is the *sole* normal field, i.e. the
            // factory's logical argument *is* the list (e.g. `Filter.And`,
            // `Filter.Or`). Factories like `Filter.In(attr, value)` or
            // `RankBy.Ann(attr, vector)` have a second normal field, so the
            // list there is a single payload argument, not a variadic one.
            let use_params = normal_fields.len() == 1;
            for (i, (prop_name, schema)) in normal_fields.iter().enumerate() {
                if i > 0 {
                    buf.write(", ");
                }
                match (use_params, schema) {
                    (true, OpenApiSchema::ArrayList { .. }) => {
                        buf.write("params ");
                        render_schema_inline(buf, schema)?;
                    }
                    // For non-variadic list payloads (e.g. `RankBy.Ann(attr,
                    // value)`, `Filter.In(attr, value)`), accept any
                    // `IEnumerable<T>` so callers can pass a `List<T>` or
                    // `T[]` interchangeably. The constructor still stores
                    // `T[]` (materialized below) so the value is safe to
                    // re-serialize across SDK retries.
                    (
                        false,
                        OpenApiSchema::ArrayList {
                            items, description, ..
                        },
                    ) => {
                        buf.write("System.Collections.Generic.IEnumerable<");
                        if let Some(generic) = shared::array_list_generic(description) {
                            buf.write(generic);
                        } else {
                            render_schema_inline(buf, items)?;
                        }
                        buf.write(">");
                    }
                    _ => render_schema_inline(buf, schema)?,
                }
                buf.write(format!(" {}", camel_case(prop_name)));
            }
            buf.write(format!(") => new {sref}{generics}("));
            for (i, (prop_name, schema)) in normal_fields.iter().enumerate() {
                if i > 0 {
                    buf.write(", ");
                }
                let arg = camel_case(prop_name);
                if !use_params && matches!(schema, OpenApiSchema::ArrayList { .. }) {
                    buf.write(format!("System.Linq.Enumerable.ToArray({arg})"));
                } else {
                    buf.write(arg);
                }
            }
            buf.write(");");
            buf.end_line();
        }
        OpenApiSchema::ArrayList { items, .. } => {
            buf.start_line();
            buf.write(format!("public static {sref} {factory_name}(params "));
            render_schema_inline(buf, items)?;
            buf.write(format!("[] items) => new {sref}(items);"));
            buf.end_line();
        }
        OpenApiSchema::String { .. } => {
            buf.writeln(format!(
                "public static {sref} {factory_name}(string value) => new {sref}(value);"
            ));
        }
        OpenApiSchema::Map {
            additional_properties,
            ..
        } => {
            buf.start_line();
            buf.write(format!("public static {sref} {factory_name}(string name, "));
            render_schema_inline(buf, additional_properties)?;
            buf.write(format!(" value) => new {sref}(name, value);"));
            buf.end_line();
        }
        // No factory for variants whose target is itself an `anyOf`: those
        // become abstract sub-types and are instantiated through their own
        // factories.
        _ => (),
    }
    Ok(())
}

fn render_schema_inline(
    buf: &mut CodegenBuf,
    schema: &OpenApiSchema,
) -> Result<(), Box<dyn Error>> {
    match schema {
        OpenApiSchema::AnyOf { .. } => buf.write("object"),
        OpenApiSchema::Object { .. } => Err("inline object schemas unsupported")?,
        OpenApiSchema::Map {
            additional_properties,
            ..
        } => {
            buf.write("System.Collections.Generic.IReadOnlyDictionary<string, ");
            render_schema_inline(buf, additional_properties)?;
            buf.write(">");
        }
        OpenApiSchema::ArrayList {
            items, description, ..
        } => {
            if let Some(generic) = shared::array_list_generic(description) {
                buf.write(generic);
            } else {
                render_schema_inline(buf, items)?;
            }
            buf.write("[]");
        }
        OpenApiSchema::ArrayTuple { .. } => Err("inline array tuple unsupported")?,
        OpenApiSchema::String { .. } => buf.write("string"),
        OpenApiSchema::Boolean { .. } => buf.write("bool"),
        OpenApiSchema::Number {
            x_turbopuffer_width,
            ..
        } => match x_turbopuffer_width {
            Some(32) => buf.write("float"),
            None | Some(64) => buf.write("double"),
            Some(w) => Err(format!("unsupported number width: {w}"))?,
        },
        OpenApiSchema::Const { .. } => Err("inline const in unsupported position")?,
        OpenApiSchema::Ref { sref, .. } => buf.write(strip_schema_ref_prefix(sref)?),
        OpenApiSchema::Any { .. } => buf.write("object"),
    }
    Ok(())
}

/// Collects the names of factory methods emitted on `name` and its ancestors,
/// so that subclass property declarations can use the `new` keyword to
/// suppress CS0108 when they collide.
fn collect_factory_names(ctx: &RenderCtx, name: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut current = Some(name);
    while let Some(cur) = current {
        if let Some(OpenApiSchema::AnyOf { any_of, .. }) = ctx.schemas.get(cur) {
            for item in any_of {
                let OpenApiSchema::Ref { sref, title } = item else {
                    continue;
                };
                let Ok(sref) = strip_schema_ref_prefix(sref) else {
                    continue;
                };
                // No factory is emitted for variants whose target is itself
                // an `anyOf`.
                if matches!(ctx.schemas.get(sref), Some(OpenApiSchema::AnyOf { .. })) {
                    continue;
                }
                let subname = title.as_deref().unwrap_or(sref);
                out.insert(pascal_case(subname.strip_prefix(cur).unwrap_or(subname)));
            }
        }
        current = ctx.inherits.get(cur).map(String::as_str);
    }
    out
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut next_upper = true;
    for c in s.chars() {
        if c == '_' {
            next_upper = true;
        } else if next_upper {
            out.extend(c.to_uppercase());
            next_upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn camel_case(s: &str) -> String {
    let pc = pascal_case(s);
    let mut chars = pc.chars();
    let mut out = String::new();
    if let Some(c) = chars.next() {
        out.extend(c.to_lowercase());
    }
    out.extend(chars);
    if is_csharp_keyword(&out) {
        format!("@{out}")
    } else {
        out
    }
}

fn sconst_to_screaming_snake(sconst: &str) -> String {
    let mut s = String::new();
    let mut chars = sconst.chars();
    if let Some(c) = chars.next() {
        s.extend(c.to_uppercase());
    }
    for c in chars {
        if c.is_uppercase() {
            s.push('_');
        }
        s.extend(c.to_uppercase());
    }
    s
}

fn escape_csharp_string(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

fn is_csharp_keyword(s: &str) -> bool {
    matches!(
        s,
        "abstract"
            | "as"
            | "base"
            | "bool"
            | "break"
            | "byte"
            | "case"
            | "catch"
            | "char"
            | "checked"
            | "class"
            | "const"
            | "continue"
            | "decimal"
            | "default"
            | "delegate"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "event"
            | "explicit"
            | "extern"
            | "false"
            | "finally"
            | "fixed"
            | "float"
            | "for"
            | "foreach"
            | "goto"
            | "if"
            | "implicit"
            | "in"
            | "int"
            | "interface"
            | "internal"
            | "is"
            | "lock"
            | "long"
            | "namespace"
            | "new"
            | "null"
            | "object"
            | "operator"
            | "out"
            | "override"
            | "params"
            | "private"
            | "protected"
            | "public"
            | "readonly"
            | "ref"
            | "return"
            | "sbyte"
            | "sealed"
            | "short"
            | "sizeof"
            | "stackalloc"
            | "static"
            | "string"
            | "struct"
            | "switch"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typeof"
            | "uint"
            | "ulong"
            | "unchecked"
            | "unsafe"
            | "ushort"
            | "using"
            | "virtual"
            | "void"
            | "volatile"
            | "while"
    )
}
