use std::collections::BTreeSet;
use std::error::Error;

use crate::codegen::{OpenApiSchema, OpenApiSpec, SCHEMA_REF_PREFIX};
use crate::util::codegen_buf::CodegenBuf;

pub fn render(spec: OpenApiSpec) -> Result<CodegenBuf, Box<dyn Error>> {
    let mut buf = CodegenBuf::with_indent("  ");
    buf.writeln("// Code generated by turbopuffer-apigen. DO NOT EDIT.");
    buf.writeln("");

    for name in spec.unmanaged_schemas {
        buf.writeln(format!("import {{ {name} }} from '../index';"));
    }
    buf.writeln("");

    let managed_names: BTreeSet<String> = spec.managed_schemas.keys().cloned().collect();

    for (name, schema) in spec.managed_schemas {
        buf.start_line();
        buf.write(format!("export type {name}<T = Record<string, any>> = "));
        render_schema(&mut buf, schema, &managed_names)?;
        buf.write(";");
        buf.end_line();
    }

    Ok(buf)
}

fn render_schema(
    buf: &mut CodegenBuf,
    schema: OpenApiSchema,
    managed: &BTreeSet<String>,
) -> Result<(), Box<dyn Error>> {
    match schema {
        OpenApiSchema::AnyOf {
            _description: _,
            any_of,
        } => {
            let expanded = any_of.len() > 3;
            if expanded {
                buf.unwrite_one(); // remove the trailing space from the last line
                buf.indent();
            }
            for (i, schema) in any_of.into_iter().enumerate() {
                if expanded {
                    buf.end_line();
                    buf.start_line();
                    buf.write("| ");
                } else if i > 0 {
                    buf.write(" | ");
                }
                render_schema(buf, schema, managed)?;
            }
            if expanded {
                buf.unindent();
            }
        }
        OpenApiSchema::Object {
            _description: _,
            _type: _,
            properties,
            required,
            title: _,
        } => {
            if !properties.keys().all(|name| required.contains(name)) {
                Err("object schemas with non-required properties not supported")?
            };
            buf.write("{ ");
            for (i, (name, schema)) in properties.into_iter().enumerate() {
                if i > 0 {
                    buf.write(", ");
                }
                buf.write(format!("{name}: "));
                render_schema(buf, schema, managed)?;
            }
            buf.write(" }")
        }
        OpenApiSchema::Map {
            _description: _,
            _type: _,
            additional_properties,
            x_turbopuffer_variant_name: _,
            title: _,
        } => {
            buf.write("Record<string, ");
            render_schema(buf, *additional_properties, managed)?;
            buf.write(">")
        }
        OpenApiSchema::ArrayList {
            description: _,
            _type: _,
            items,
            title: _,
        } => {
            render_schema(buf, *items, managed)?;
            buf.write("[]");
        }
        OpenApiSchema::ArrayTuple {
            additional_items: true,
            ..
        } => Err("tuple-type arrays with `items: true` unsupported")?,
        OpenApiSchema::ArrayTuple {
            _description: _,
            _type: _,
            additional_items: false,
            prefix_items,
            x_turbopuffer_variant_name: _,
            x_turbopuffer_variant_drop_on_conflict: _,
            title: _,
        } => {
            buf.write("[");
            for (i, schema) in prefix_items.into_iter().enumerate() {
                if i > 0 {
                    buf.write(", ");
                }
                render_schema(buf, schema, managed)?;
            }
            buf.write("]")
        }
        OpenApiSchema::String {
            _description: _,
            _type: _,
            x_turbopuffer_variant_name: _,
            title,
        } => {
            if title.as_deref() == Some("attr") {
                buf.write("keyof T & string");
            } else {
                buf.write("string");
            }
        }
        OpenApiSchema::Number {
            _description: _,
            _type: _,
            title: _,
            x_turbopuffer_width: _,
        } => buf.write("number"),
        OpenApiSchema::Boolean {
            _description: _,
            _type: _,
            title: _,
        } => buf.write("boolean"),
        OpenApiSchema::Const {
            _description: _,
            sconst,
            title: _,
        } => buf.write(format!("'{sconst}'")),
        OpenApiSchema::Ref { sref, title: _ } => match sref.strip_prefix(SCHEMA_REF_PREFIX) {
            None => Err(format!("unsupported reference: {sref}"))?,
            Some(name) => {
                buf.write(name);
                if managed.contains(name) {
                    buf.write("<T>");
                }
            }
        },
        OpenApiSchema::Any { .. } => buf.write("any"),
    }
    Ok(())
}
